const BUILDING_CUSTOMIZER_LABEL = "Customize Building";
const UPLOAD_FILE_LABEL = "Upload File";
const TOTAL_HEIGHT_LABEL = "Total Height";

export { BUILDING_CUSTOMIZER_LABEL, UPLOAD_FILE_LABEL, TOTAL_HEIGHT_LABEL };
